on: [push, pull_request]

permissions:
  id_token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    name: Coverage
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - run: npm i
      - run: npm run testAll
      - uses: codecov/codecov-action@v5
        with:
          use_oidc: true
